### ISSUE TITLE
books sold by villagers keep the "work cost" nbt of the book on the lectern 

### ISSUE THREAD

**Issue by CodeF53** [mistrk7/librarians-balance#1]
books sold by villagers keep the "work cost" nbt of the book on the lectern 
making combining 2 prot 3 books cost 10 levels

![image](https://user-images.githubusercontent.com/37855219/232138957-b59b932c-3ee0-44a1-bceb-7b4c6baa0a43.png)

**Comment by mistrk7** [comment]
Thanks. This bug exists due to how Librarians grab data from the book in their lectern. Modifying and fixing this now.

**Comment by mistrk7** [comment]
fixed. to be released in v1.2
