### ISSUE TITLE
The mod version isnt working on my self-hosting server

### ISSUE THREAD

**Issue by pacw64000** [mistrk7/librarians-balance#10]
I was trying to use this to limit myself because i am kind of a tryhard so my friends made me install it.

my server is hosted using **Quilt 0.26.3** on **1.21**
mod version 3.2, downloaded from modrinth
based on the images i saw and some tests i did nothing happens when i try to right-click the lectern so now i am resorting to post here, even if i know how to _"Program"_ on minecraft i dont know anything about the logic behind the lectern nor the mod itself

**Comment by mistrk7** [comment]
I'm not sure. Try running `/function libal:load`. What other mods do you have installed?
