### ISSUE TITLE
Mending becomes Bane of Arthropods I

### ISSUE THREAD

**Issue by sh0tybumbati** [mistrk7/librarians-balance#13]
Every time I see a mending librarian, the next time I trade with them, they sell Bane of Arthropods I.
This has happened to me for 4 mending villagers now, and even to the mending books I buy from them when I manage to purchase it the first time I see the trade-
Whats going on here?
I checked and I do allow them to sell mending books in the config-

**Comment by mistrk7** [comment]
this is the default mending behaviour. are you sure that you disabled it? what version are you on?

**Comment by sh0tybumbati** [comment]
When i opened the config, it seemed to have been set to "allow mending" but i guess it wasn't since it was set to 0 not 1-
I was using the Fabric packaged version on 1.20, but switched to the zip/datapack version, but I think it having been set to 0 might have been the cause- I'll try finding another mending guy after having set it to 1

**Comment by mistrk7** [comment]
I feel like you're using an older version of 1.20. If you redownload, make sure it's on v3.4 because it seems to work fine for me there.

**Comment by sh0tybumbati** [comment]
Hmm I'm using the v3.4 version of the pack, but i am indeed running 1.20.0 on Fabric- is that why? Should I switch to an older version of the datapack?

**Comment by mistrk7** [comment]
No you shouldn't. hm. Are you using the '/function libal:config' command correctly? 'no_mending' should get set to -1 once you toggle it and that should be it. It only got set to zero on older and broken versions.

https://github.com/user-attachments/assets/33851d31-fe71-4d28-b77b-2518683f5240

**Comment by sh0tybumbati** [comment]
OHHH I interpreted that as "allow mending" from the chat dialogues, so I've been setting it to 1
I see now that I have just no reading comprehension

**Comment by mistrk7** [comment]
All good. I will change the wording to be more consistent with the rest of the versions :)
