### ISSUE TITLE
Is there a way to disable Limit Random Trades in every world?

### ISSUE THREAD

**Issue by nickademas** [mistrk7/librarians-balance#4]
I want the "Limit Random Trades" feature to be disabled in every world without entering the command. Is there any option for this? If not, will deleting the trades_filter.mcfunction file work?

**Comment by mistrk7** [comment]
In the Datapack, you can set the default command of `cap_enchant_level` to be disabled with a value of 0 in the function file `a_settings.mcfunction`

Location:
```
data/libal/functions/a_settings.mcfunction
```

You can't easily do this with the mod version though as it is already pre compiled. hope this helps!
